(() => {
'use strict';
const DATA=window.FARSIYAR_DATA, cfg=window.FARSYAR_SUPABASE_URL&&window.FARSYAR_SUPABASE_ANON_KEY;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={role:null,room:null,classId:null,rosterId:null,name:null,pin:null,client:null,channel:null,cls:null,roster:[],scores:[],responses:[],missionType:'written',board:{strokes:[],redo:[]},drawing:false,tool:'pen',last:null,lesson:1};
const localKey='farsiyar_student_session_v6';
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove('show'),3200)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function faNum(n){return String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d])}
function norm(s){return String(s??'').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[ۀة]/g,'ه').replace(/[أإ]/g,'ا').replace(/ؤ/g,'و').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[\u200c\u200f]/g,' ').replace(/[.,،؛:!?؟«»"'()\[\]{}]/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
function similarity(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;const A=a.split(' '),B=b.split(' '), used=new Set();let hit=0;for(const x of A){let best=-1,bs=0;B.forEach((y,i)=>{if(used.has(i))return;const d=lev(x,y),sim=1-d/Math.max(x.length,y.length,1);if(sim>bs){bs=sim;best=i}});if(bs>=.72){hit+=bs;used.add(best)}}return hit/Math.max(A.length,B.length)}
function lev(a,b){const d=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
function lesson(){return DATA.lessons.find(x=>x.n===state.lesson)||DATA.lessons[0]}
function book(page){return `book/chaharom-farsi-1404.pdf#page=${page}`}
function show(id){$$('.screen').forEach(x=>x.classList.add('hidden'));$( '#'+id)?.classList.remove('hidden');$('#logoutBtn').classList.toggle('hidden',!['teacherPanel','studentPanel'].includes(id));window.scrollTo({top:0,behavior:'smooth'})}
function populateLessons(){const opts=DATA.lessons.map(x=>`<option value="${x.n}">درس ${faNum(x.n)} — ${esc(x.title)}</option>`).join('');$('#setupLesson').innerHTML=opts;$('#lessonSelect').innerHTML=opts}
function initTheme(){const saved=localStorage.getItem('farsiyar_theme');if(saved==='dark'||(!saved&&matchMedia('(prefers-color-scheme: dark)').matches))document.body.classList.add('dark');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('farsiyar_theme',document.body.classList.contains('dark')?'dark':'light')}}
async function init(){populateLessons();initTheme();bind();$('#loading').classList.add('hidden');$('#app').classList.remove('hidden');if(!cfg){toast('تنظیمات Supabase در supabase-config.js کامل نیست.');return}state.client=supabase.createClient(window.FARSYAR_SUPABASE_URL,window.FARSYAR_SUPABASE_ANON_KEY);const {data}=await state.client.auth.getSession();if(data.session){state.role='teacher';await loadTeacherSession(data.session)}else{const raw=localStorage.getItem(localKey);if(raw){try{const s=JSON.parse(raw);Object.assign(state,s);await studentLoad(true)}catch{localStorage.removeItem(localKey)}}}}
function bind(){ $$('[data-show]').forEach(b=>b.onclick=()=>show(b.dataset.show));$('#teacherLoginForm').onsubmit=teacherLogin;$('#loadRoster').onclick=loadRoster;$('#studentJoinForm').onsubmit=studentJoin;$('#createClassBtn').onclick=createClass;$('#logoutBtn').onclick=logout;$('#saveNotice').onclick=saveNotice;$('#lessonSelect').onchange=()=>{state.lesson=+$('#lessonSelect').value;renderLesson()};$('#setupLesson').onchange=()=>state.lesson=+$('#setupLesson').value;$('#saveRoster').onclick=saveRoster;$('#openStudentBook').onclick=()=>window.open(book(lesson().page),'_blank');$('#studentVideo').onclick=()=>window.open(lesson().video,'_blank');$('#printReport').onclick=()=>window.print();$('#exportJson').onclick=exportReport;$$('#teacherTabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$('[data-mtype]').forEach(b=>b.onclick=()=>{state.missionType=b.dataset.mtype;renderMissionEditor()});$$('[data-tool]').forEach(b=>b.onclick=toolModal);$$('[data-board]').forEach(b=>b.onclick=boardAction);$('#penColor').oninput=e=>state.board.color=e.target.value;$('#penSize').oninput=e=>state.board.size=+e.target.value;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');window.addEventListener('resize',()=>drawBoard());}
async function teacherLogin(e){e.preventDefault();if(!state.client)return toast('Supabase تنظیم نشده است.');const email=$('#teacherEmail').value.trim(),password=$('#teacherPassword').value;if(!email||!password)return;const {data,error}=await state.client.auth.signInWithPassword({email,password});if(error){const m=String(error.message).toLowerCase();toast(m.includes('invalid login')?'ایمیل یا رمز عبور نادرست است.':m.includes('not confirmed')?'ایمیل حساب هنوز تأیید نشده است.':error.message);return}state.role='teacher';await loadTeacherSession(data.session)}
async function loadTeacherSession(){show('teacherPanel');$('#teacherWelcome').textContent='حساب معلم با Supabase Auth وارد شده است.';const {data,error}=await state.client.from('farsiyar_classes').select('*').order('created_at',{ascending:false}).limit(1);if(error){toast('جدول‌های فارسی‌یار آماده نیستند؛ supabase-schema.sql را اجرا کنید.');return}if(data?.[0]){await openTeacherClass(data[0])}else{$('#teacherSetup').classList.remove('hidden');$('#teacherWorkspace').classList.add('hidden')}}
function randomRoom(){return 'FAR-'+String(Math.floor(1000+Math.random()*9000))}
function pins(names){return names.map(()=>String(Math.floor(100000+Math.random()*900000)))}
async function createClass(){const {data:user}=await state.client.auth.getUser();if(!user.user)return toast('ابتدا وارد حساب معلم شوید.');const names=$('#rosterNames').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,29);const count=Math.min(29,Math.max(1,+$('#rosterCount').value||29));while(names.length<count)names.push(`دانش‌آموز ${names.length+1}`);const room=randomRoom(), lessonIndex=+$('#setupLesson').value||1;const {data:c,error}=await state.client.from('farsiyar_classes').insert({owner_id:user.user.id,room_code:room,title:$('#classTitle').value.trim()||'کلاس فارسی امروز',lesson_index:lessonIndex}).select().single();if(error){toast('ساخت کلاس ناموفق بود: '+error.message);return}const ps=pins(names);const {data:roster,error:re}=await state.client.rpc('teacher_replace_roster',{p_class_id:c.id,p_names:names,p_pins:ps});
if(re){await state.client.from('farsiyar_classes').delete().eq('id',c.id);toast('تابع teacher_replace_roster در SQL موجود نیست. نسخه کامل schema را اجرا کنید.');return}
state.roster=roster||[];state.pinMap=Object.fromEntries((roster||[]).map((r,i)=>[r.student_name,ps[i]]));await openTeacherClass({...c,lesson_index:lessonIndex});showPinList(ps)}
async function loadRoster(){const code=$('#joinCode').value.trim().toUpperCase();if(!/^FAR-\d{4}$/.test(code))return toast('کد کلاس باید مثل FAR-1234 باشد.');const {data,error}=await state.client.rpc('get_public_class',{p_room_code:code});if(error||!data)return toast(error?.message||'کد کلاس پیدا نشد.');state.joinPublic=data;const sel=$('#studentName');sel.innerHTML=data.roster.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join('');$('#studentNameWrap,#studentPinWrap,#joinBtn').forEach(x=>x.classList.remove('hidden'));$('#joinHint').textContent=`کلاس «${data.title}» پیدا شد. نام خودت و رمزت را وارد کن.`}
async function studentJoin(e){e.preventDefault();const code=$('#joinCode').value.trim().toUpperCase(),name=$('#studentName').value,pin=$('#studentPin').value.trim();if(!pin)return toast('رمز ورود دانش‌آموز را وارد کن.');const {data,error}=await state.client.rpc('student_join',{p_room_code:code,p_student_name:name,p_pin:pin});if(error){toast(error.message.includes('رمز')?error.message:'ورود به کلاس انجام نشد: '+error.message);return}Object.assign(state,{role:'student',room:code,rosterId:data.roster_id,name:data.name,pin,classId:data.class_id});localStorage.setItem(localKey,JSON.stringify({role:'student',room:state.room,rosterId:state.rosterId,name:state.name,pin:state.pin,classId:state.classId}));await studentLoad(false)}
async function studentLoad(silent){const {data,error}=await state.client.rpc('get_public_class',{p_room_code:state.room});if(error||!data){if(!silent)toast('کلاس دیگر در دسترس نیست.');localStorage.removeItem(localKey);show('landing');return}state.cls=data;state.classId=data.id;state.lesson=data.lesson_index;state.roster=data.roster;await renderStudent();subscribeStudent();show('studentPanel')}
async function openTeacherClass(c){state.cls=c;state.room=c.room_code;state.classId=c.id;state.lesson=c.lesson_index||1;$('#teacherRoomCode,#rRoom').forEach?.(()=>{});$('#teacherRoomCode').textContent=state.room;$('#rRoom').textContent=state.room;$('#teacherSetup').classList.add('hidden');$('#teacherWorkspace').classList.remove('hidden');$('#lessonSelect').value=state.lesson;$('#setupLesson').value=state.lesson;await refreshTeacher();subscribeTeacher()}
async function refreshTeacher(){const [ro,sc,re]=await Promise.all([state.client.from('farsiyar_roster').select('id,student_name,active').eq('class_id',state.classId).order('student_name'),state.client.from('farsiyar_scores').select('roster_id,student_name,points').eq('class_id',state.classId).order('points',{ascending:false}),state.client.from('farsiyar_responses').select('*').eq('class_id',state.classId).order('created_at',{ascending:false}).limit(200)]);state.roster=ro.data||[];state.scores=sc.data||[];state.responses=re.data||[];renderTeacher();}
function subscribeTeacher(){if(state.channel)state.client.removeChannel(state.channel);state.channel=state.client.channel('farsiyar-'+state.classId).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_classes',filter:'id=eq.'+state.classId},p=>{state.cls=p.new;state.lesson=p.new.lesson_index;renderTeacher()}).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_responses',filter:'class_id=eq.'+state.classId},()=>refreshTeacher()).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_scores',filter:'class_id=eq.'+state.classId},()=>refreshTeacher()).subscribe()}
function subscribeStudent(){if(state.channel)state.client.removeChannel(state.channel);state.channel=state.client.channel('student-'+state.classId).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_public_state',filter:'room_code=eq.'+state.room},p=>{state.cls={...state.cls,...p.new};state.lesson=p.new.lesson_index;renderStudent()}).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_public_scores',filter:'room_code=eq.'+state.room},()=>renderStudent()).subscribe()}
function renderTeacher(){if(!state.cls)return;$('#teacherRoomCode').textContent=state.room;$('#mStudents').textContent=faNum(state.roster.length);$('#mResponses').textContent=faNum(state.responses.length);const avg=state.scores.length?state.scores.reduce((a,b)=>a+b.points,0)/state.scores.length:0;$('#mAverage').textContent=faNum(avg.toFixed(1));$('#noticeInput').value=state.cls.notice||'';renderLesson();renderMissionEditor();renderResponses();renderLeaderboard('#topScores');renderRoster();renderReport()}
function renderLesson(){const l=lesson();$('#lessonTitle').textContent=`درس ${faNum(l.n)}: ${l.title}`;$('#lessonDesc').textContent=`صفحه چاپی ${faNum(l.print)} — مقصد داخلی واقعی PDF: صفحه ${faNum(l.page)}.`;const stages=DATA.stages.map((s,i)=>`<div class="route-item"><div><b>${faNum(i+1)}. ${esc(s)}</b><small>${i===0?'شروع و فعال‌سازی':i===1?'متن‌خوانی و فهم':i===2?'واژه و املا':i===3?'بازی و تمرین':'جمع‌بندی و ارزشیابی'}</small></div><button onclick="window.open('${book(l.page)}','_blank')">بازکردن</button></div>`).join('');$('#lessonRoute').innerHTML=stages;const ex=DATA.extras||[];$('#bookExtras').innerHTML=ex.map(x=>`<button class="extra-book" onclick="window.open('${book(x.page)}','_blank')"><span>📘</span><b>${esc(x.title)}</b><small>صفحه ${faNum(x.print)}</small></button>`).join('');$('#lessonVideo').innerHTML=`<a class="btn secondary" href="${esc(l.video)}" target="_blank" rel="noopener">▶️ بازکردن ویدئوی ${esc(l.title)}</a><span class="muted"> ${l.video.includes('watch')?'لینک مستقیم بررسی‌شده':'لینک جست‌وجوی موضوعی'}</span>`}
function renderMissionEditor(){const box=$('#missionEditor');if(!box)return;let html='';if(state.missionType==='mcq')html=`<div class="mission-editor"><label>سؤال<input id="miQuestion" placeholder="سؤال چهارگزینه‌ای"></label><div class="options">${[0,1,2,3].map(i=>`<input id="miO${i}" placeholder="گزینه ${i+1}">`).join('')}</div><label>گزینه درست<select id="miCorrect"><option value="0">۱</option><option value="1">۲</option><option value="2">۳</option><option value="3">۴</option></select></label><button class="btn primary" onclick="publishMission('mcq')">انتشار مأموریت</button></div>`;else if(state.missionType==='dictation')html=`<div class="mission-editor"><label>متن صحیح دیکته<input id="miText" placeholder="مثلاً: بهار فصل زیبایی است"></label><label>متن شنیداری<input id="miSpeak" placeholder="اگر خالی باشد از متن صحیح استفاده می‌شود"></label><button class="btn primary" onclick="publishMission('dictation')">انتشار دیکته</button></div>`;else if(state.missionType==='sentence')html=`<div class="mission-editor"><label>کلمات یا موضوع جمله‌سازی<input id="miWords" placeholder="مثلاً: مدرسه، کتاب، دانایی"></label><label>نمونه پاسخ اختیاری<input id="miAnswer" placeholder="برای امتیازدهی خودکار دقیق‌تر"></label><button class="btn primary" onclick="publishMission('sentence')">انتشار مأموریت</button></div>`;else html=`<div class="mission-editor"><label>سؤال / دستور مأموریت<input id="miQuestion" placeholder="مثلاً: سه واژه از درس امروز بنویس."></label><label>پاسخ مرجع اختیاری<input id="miAnswer" placeholder="برای امتیازدهی خودکار"></label><button class="btn primary" onclick="publishMission('written')">انتشار مأموریت</button></div>`;box.innerHTML=html}
window.publishMission=async type=>{let m={type,active:true,created_at:Date.now()};if(type==='mcq'){m.question=$('#miQuestion').value;m.options=[0,1,2,3].map(i=>$('#miO'+i).value);m.correct=+$('#miCorrect').value}else if(type==='dictation'){m.text=$('#miText').value;m.speak=$('#miSpeak').value||m.text}else if(type==='sentence'){m.words=$('#miWords').value;m.answer=$('#miAnswer').value}else{m.question=$('#miQuestion').value;m.answer=$('#miAnswer').value}if(!m.question&&type!=='dictation')return toast('متن مأموریت را وارد کنید.');const {error}=await state.client.from('farsiyar_classes').update({mission:m,updated_at:new Date().toISOString()}).eq('id',state.classId);if(error)toast(error.message);else toast('مأموریت برای کلاس منتشر شد.');};
window.closeMission=async()=>{const {error}=await state.client.from('farsiyar_classes').update({mission:{active:false}}).eq('id',state.classId);if(error)toast(error.message);else toast('مأموریت بسته شد.')};
async function saveNotice(){const {error}=await state.client.from('farsiyar_classes').update({notice:$('#noticeInput').value.slice(0,1000),updated_at:new Date().toISOString()}).eq('id',state.classId);toast(error?error.message:'پیام زنده ارسال شد.')}
function renderResponses(){const box=$('#responses');$('#responseCount').textContent=faNum(state.responses.length);if(!state.responses.length){box.innerHTML='<div class="muted">هنوز پاسخی ثبت نشده است.</div>';return}box.innerHTML=state.responses.map(r=>`<div class="response"><div class="meta"><b>${esc(r.student_name)}</b><span>${new Date(r.created_at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}</span></div><div>${esc(r.answer)}</div><div class="response-actions"><span class="muted">امتیاز خودکار: ${faNum(r.score)}</span>${[1,2,3].map(n=>`<button class="score-btn" onclick="manualScore('${r.roster_id}',${n})">+${n}</button>`).join('')}</div></div>`).join('')}
window.manualScore=async(rid,n)=>{const {data,error}=await state.client.rpc('teacher_add_score',{p_class_id:state.classId,p_roster_id:rid,p_delta:n});if(error)toast(error.message);else toast(`امتیاز ثبت شد: ${data}`)};
function renderLeaderboard(target){const box=$(target);const arr=[...state.scores].sort((a,b)=>b.points-a.points).slice(0,5);box.innerHTML=arr.length?arr.map((s,i)=>`<div class="leader-row"><span class="rank">${faNum(i+1)}</span><b>${esc(s.student_name)}</b><strong>${faNum(s.points)}</strong></div>`).join(''):'<div class="muted">هنوز امتیازی ثبت نشده.</div>'}
function renderRoster(){if(!$('#rosterEditor'))return;$('#rosterEditor').value=state.roster.map(x=>x.student_name).join('\n');const p=state.pinMap||{};$('#pinList').innerHTML=state.roster.map(r=>`<div class="pin-item"><span>${esc(r.student_name)}</span><code>${p[r.student_name]||'••••••'}</code></div>`).join('')}
async function saveRoster(){const names=$('#rosterEditor').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,29);const ps=pins(names);const {data,error}=await state.client.rpc('teacher_replace_roster',{p_class_id:state.classId,p_names:names,p_pins:ps});if(error){toast(error.message);return}state.roster=data||[];state.pinMap=Object.fromEntries((data||[]).map((r,i)=>[r.student_name,ps[i]]));showPinList(ps);await refreshTeacher();toast('فهرست و رمزهای ورود ذخیره شد.')}
function showPinList(ps){if(!state.pinMap)return;$('#pinList').innerHTML=state.roster.map((r,i)=>`<div class="pin-item"><span>${esc(r.student_name)}</span><code>${state.pinMap[r.student_name]||ps[i]||''}</code></div>`).join('')}
function renderReport(){const scores=[...state.scores].sort((a,b)=>b.points-a.points),sum=scores.reduce((a,b)=>a+b.points,0),avg=scores.length?sum/scores.length:0;$('#rResponses').textContent=faNum(state.responses.length);$('#rAverage').textContent=faNum(avg.toFixed(1));$('#rMax').textContent=faNum(scores[0]?.points||0);$('#rRoom').textContent=state.room;$('#reportTable').innerHTML=`<table><thead><tr><th>رتبه</th><th>نام</th><th>امتیاز</th></tr></thead><tbody>${scores.map((s,i)=>`<tr><td>${faNum(i+1)}</td><td>${esc(s.student_name)}</td><td>${faNum(s.points)}</td></tr>`).join('')}</tbody></table>`}
function tab(id){$$('.tab-panel').forEach(x=>x.classList.remove('active'));$('#tab-'+id).classList.add('active');$$('#teacherTabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='board')setTimeout(initBoard,20)}
function toolModal(e){const t=e.currentTarget.dataset.tool;$('#modal').classList.remove('hidden');if(t==='wheel'){$('#modalBody').innerHTML=`<h3>🎲 قرعه‌کشی زنده</h3><p>از فهرست ${faNum(state.roster.length)} نفر یک نفر به‌صورت تصادفی انتخاب می‌شود.</p><button class="btn primary" id="spinBtn">چرخاندن</button><div id="winner" style="font-size:35px;font-weight:900;margin:25px 0;text-align:center">—</div>`;$('#spinBtn').onclick=()=>{let i=0;const arr=state.roster;const iv=setInterval(()=>{$('#winner').textContent=arr[i++%arr.length]?.student_name||'—'},80);setTimeout(()=>{clearInterval(iv);const w=arr[Math.floor(Math.random()*arr.length)];$('#winner').textContent='🎉 '+w.student_name},1400)}}else if(t==='timer'){$('#modalBody').innerHTML=`<h3>⏱ تایمر کلاس</h3><input id="timerMin" type="number" min="1" value="5"><button class="btn primary" id="timerStart">شروع</button><div id="timerOut" style="font-size:55px;text-align:center;margin:25px">05:00</div>`;$('#timerStart').onclick=()=>{let s=(+$('#timerMin').value||5)*60;const out=$('#timerOut');clearInterval(window.timer);window.timer=setInterval(()=>{s--;out.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(s<=0){clearInterval(window.timer);toast('زمان تمام شد!')}},1000)}}else window.open(book(lesson().page),'_blank')}
function initBoard(){const c=$('#boardCanvas');if(!c||c.dataset.bound)return;c.dataset.bound='1';c.addEventListener('pointerdown',e=>{state.drawing=true;c.setPointerCapture(e.pointerId);state.last=pt(c,e);state.board.strokes.push({tool:state.tool,color:state.board.color||$('#penColor').value,size:state.board.size||+$('#penSize').value,pts:[state.last]});state.board.redo=[];drawBoard()});c.addEventListener('pointermove',e=>{if(!state.drawing)return;const p=pt(c,e);state.board.strokes.at(-1).pts.push(p);state.last=p;drawBoard()});['pointerup','pointercancel'].forEach(ev=>c.addEventListener(ev,()=>{state.drawing=false;syncBoard()}));drawBoard()}
function pt(c,e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
function drawBoard(){const c=$('#boardCanvas');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);for(const s of state.board.strokes){x.beginPath();x.lineCap='round';x.lineJoin='round';x.lineWidth=s.size;x.strokeStyle=s.tool==='eraser'?'#fff':s.color;for(let i=0;i<s.pts.length;i++){const p=s.pts[i];i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y)}x.stroke()}drawPreview()}
function drawPreview(){const c=$('#studentBoardPreview');if(!c)return;const x=c.getContext('2d'),src=$('#boardCanvas');if(src)x.drawImage(src,0,0,c.width,c.height)}
async function syncBoard(){const {error}=await state.client.from('farsiyar_classes').update({board_state:state.board.strokes,updated_at:new Date().toISOString()}).eq('id',state.classId);if(error)toast('ذخیره تخته ناموفق بود.')}
function boardAction(e){const a=e.currentTarget.dataset.board;if(a==='undo'){const x=state.board.strokes.pop();if(x)state.board.redo.push(x);drawBoard();syncBoard()}else if(a==='redo'){const x=state.board.redo.pop();if(x)state.board.strokes.push(x);drawBoard();syncBoard()}else if(a==='clear'){state.board.redo=[];state.board.strokes=[];drawBoard();syncBoard()}else state.tool=a}
async function renderStudent(){const c=state.cls||{};const l=lesson();$('#studentHello').textContent=state.name;$('#studentRoomCode').textContent=state.room;$('#studentLessonText').textContent=`درس ${faNum(l.n)}: ${l.title}`;$('#studentLessonDesc').textContent=`صفحه ${faNum(l.print)} کتاب؛ مقصد PDF صفحه ${faNum(l.page)}.`;$('#studentNotice').textContent=c.notice||'پیامی از معلم نیست.';const scores=await fetchPublicScores();$('#studentScore').textContent=faNum(scores.find(s=>s.roster_id===state.rosterId)?.points||0);state.scores=scores;renderLeaderboard('#studentLeaderboard');renderStudentMission(c.mission);drawStudentBoard(c.board_state||[]);}
async function fetchPublicScores(){const {data,error}=await state.client.rpc('get_public_scores',{p_room_code:state.room});return error?[]:(data||[])}
function renderStudentMission(m){const box=$('#studentMission');if(!m?.active){$('#studentMissionBadge').textContent='در انتظار';box.innerHTML='<p class="muted">معلم هنوز مأموریتی منتشر نکرده است.</p>';return}$('#studentMissionBadge').textContent='زنده';let h='';if(m.type==='mcq')h=`<h3>${esc(m.question)}</h3><div class="tool-grid">${m.options.map((o,i)=>`<button onclick="submitStudent('${esc(m.type)}',${i})">${faNum(i+1)}. ${esc(o)}</button>`).join('')}</div>`;else if(m.type==='dictation')h=`<p>🔊 متن را گوش کن و بنویس.</p><button class="btn secondary" id="speakBtn">پخش دیکته</button><textarea id="studentAnswer" rows="4" placeholder="پاسخ خودت را بنویس"></textarea><button class="btn primary" onclick="submitStudent('dictation')">ارسال</button>`;else if(m.type==='sentence')h=`<h3>با این کلمات جمله بساز:</h3><p class="success">${esc(m.words||'')}</p><textarea id="studentAnswer" rows="4" placeholder="جمله خودت را بنویس"></textarea><button class="btn primary" onclick="submitStudent('sentence')">ارسال</button>`;else h=`<h3>${esc(m.question||'')}</h3><textarea id="studentAnswer" rows="4" placeholder="پاسخت را بنویس"></textarea><button class="btn primary" onclick="submitStudent('written')">ارسال</button>`;box.innerHTML=h;if(m.type==='dictation')$('#speakBtn').onclick=()=>speechSynthesis?.speak(new SpeechSynthesisUtterance(m.speak||m.text||''));}
window.submitStudent=async(type,choice)=>{const m=state.cls.mission;if(!m?.active)return;let answer='',score=0;if(type==='mcq'){answer=String(choice);score=choice===m.correct?3:0}else{answer=$('#studentAnswer')?.value||'';if(!answer)return toast('اول پاسخ را وارد کن.');if(type==='dictation')score=similarity(answer,m.text)>=.92?3:similarity(answer,m.text)>=.72?1:0;else if(m.answer)score=similarity(answer,m.answer)>=.92?3:similarity(answer,m.answer)>=.72?1:0}const {data,error}=await state.client.rpc('submit_student_response',{p_room_code:state.room,p_student_name:state.name,p_pin:state.pin,p_kind:type,p_answer:answer,p_auto_score:score});if(error)toast(error.message);else toast(`پاسخ ثبت شد؛ امتیاز این مأموریت: ${faNum(data.score)}`)};
function drawStudentBoard(strokes){const c=$('#studentBoardPreview');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);for(const s of (strokes||[])){x.beginPath();x.lineCap='round';x.lineJoin='round';x.lineWidth=s.size;x.strokeStyle=s.tool==='eraser'?'#fff':s.color;const scaleX=c.width/1200,scaleY=c.height/620;s.pts.forEach((p,i)=>i?x.lineTo(p.x*scaleX,p.y*scaleY):x.moveTo(p.x*scaleX,p.y*scaleY));x.stroke()}}
async function logout(){await state.client?.auth.signOut();localStorage.removeItem(localKey);if(state.channel)state.client.removeChannel(state.channel);location.reload()}
function exportReport(){const out={room:state.room,title:state.cls?.title,lesson:lesson(),scores:state.scores,responses:state.responses,exported_at:new Date().toISOString()};const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`FarsiYar-${state.room}-report.json`;a.click();URL.revokeObjectURL(a.href)}
// helper RPC for secure server-side PIN hashing/roster replacement is defined in schema below.
window.addEventListener('load',init);
})();
