(() => {
'use strict';
const {lessons,routes}=window.FarsiYarData;
const $=id=>document.getElementById(id);
const sbUrl=window.FARSYAR_SUPABASE_URL;
const sbKey=window.FARSYAR_SUPABASE_PUBLISHABLE_KEY;
let supabase=null, teacherUser=null, classRow=null, channel=null, roomChannel=null, studentChannel=null;
let responses=[], scores=[], roster=Array(29).fill(''), selectedMissionType='text', currentMission=null;
let boardState=[], drawing=false,lastPoint=null;

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function faNum(n){return String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function errorText(err){const m=(err?.message||String(err||'')).toLowerCase();if(!navigator.onLine)return'اینترنت قطع است. اتصال اینترنت را بررسی کنید.';if(m.includes('invalid login credentials'))return'ایمیل یا رمز عبور اشتباه است.';if(m.includes('email not confirmed'))return'ایمیل این حساب هنوز تأیید نشده است.';if(m.includes('user not found')||m.includes('user'))return'کاربر ساخته نشده یا حساب قابل دسترسی نیست.';if(m.includes('invalid api key')||m.includes('apikey')||m.includes('jwt'))return'کلید Supabase اشتباه یا نامعتبر است.';if(m.includes('relation')||m.includes('does not exist'))return'جدول‌ها یا تابع‌های فارسی‌یار در Supabase ساخته نشده‌اند. SQL کامل پروژه را اجرا کنید.';if(m.includes('permission')||m.includes('row-level'))return'دسترسی RLS اجازه این عملیات را نمی‌دهد؛ مالکیت کلاس و policyها را بررسی کنید.';return`خطای اتصال یا سرویس: ${esc(err?.message||err||'نامشخص')}`}
function setConnection(ok,msg){const c=$('connection');c.className='connection '+(ok?'ok':'bad');c.textContent=(ok?'● ':'● ')+(msg|| (ok?'متصل':'قطع'))}
async function initSupabase(){if(!sbUrl||!sbKey){setConnection(false,'تنظیم نشده');return false}try{if(!window.supabase?.createClient){setConnection(false,'کتابخانه بارگذاری نشد');return false}supabase=window.supabase.createClient(sbUrl,sbKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await supabase.auth.getSession();if(error)throw error;teacherUser=data.session?.user||null;setConnection(true,'Supabase آماده');if(teacherUser)await enterTeacher();supabase.auth.onAuthStateChange(async(_e,session)=>{teacherUser=session?.user||null;if(teacherUser)await enterTeacher();else leaveTeacherUI()});return true}catch(e){setConnection(false,'خطا');$('authError').textContent=errorText(e);return false}}
async function signIn(){const email=$('teacherEmail').value.trim(),password=$('teacherPassword').value;if(!email||!password){$('authError').textContent='ایمیل و رمز عبور را کامل وارد کنید.';return}if(!supabase){$('authError').textContent='اتصال Supabase آماده نیست.';return}$('loginBtn').disabled=true;$('authError').textContent='';try{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;teacherUser=data.user;await enterTeacher();toast('ورود موفق بود.')}catch(e){$('authError').textContent=errorText(e)}finally{$('loginBtn').disabled=false}}
async function signOut(){if(supabase)await supabase.auth.signOut();teacherUser=null;leaveTeacherUI();toast('از حساب معلم خارج شدی.')}
function leaveTeacherUI(){$('authBox').classList.remove('hidden');$('teacherApp').classList.add('hidden');classRow=null;responses=[];scores=[];if(channel){supabase.removeChannel(channel);channel=null} if(roomChannel){supabase.removeChannel(roomChannel);roomChannel=null}}
async function enterTeacher(){if(!teacherUser)return;$('authBox').classList.add('hidden');$('teacherApp').classList.remove('hidden');await loadTeacherClass();renderRoster();}
async function loadTeacherClass(){try{const {data,error}=await supabase.from('farsiyar_classes').select('*').eq('owner_id',teacherUser.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(data){classRow=data;hydrateFromClass(data);subscribeTeacher();}else await createClass();}catch(e){$('authError').textContent=errorText(e)}}
function hydrateFromClass(c){roster=Array.isArray(c.roster)?c.roster.slice(0,29).concat(Array(Math.max(0,29-c.roster.length)).fill('')).slice(0,29):Array(29).fill('');currentMission=c.mission||null;boardState=Array.isArray(c.board_state)?c.board_state:[];$('roomCode').textContent=c.room_code||'----';$('liveLink').textContent=c.room_code?`${location.origin}${location.pathname}?class=${encodeURIComponent(c.room_code)}`:'';$('lessonSelect').value=String(c.lesson_index??0);renderLesson();renderMissionPreview();drawBoard($('teacherCanvas'),boardState);renderScores();$('noticeInput').value='';}
async function createClass(){if(!teacherUser)return;try{const code=await uniqueCode();const {data,error}=await supabase.from('farsiyar_classes').insert({owner_id:teacherUser.id,room_code:code,title:'کلاس فارسی چهارم',lesson_index:0,roster:roster,mission:null,notice:'',board_state:[]}).select('*').single();if(error)throw error;classRow=data;responses=[];scores=[];subscribeTeacher();hydrateFromClass(data);toast(`کلاس ${code} ساخته شد.`)}catch(e){toast(errorText(e))}}
async function uniqueCode(){for(let i=0;i<20;i++){const code='FAR-'+String(Math.floor(Math.random()*10000)).padStart(4,'0');const {data}=await supabase.from('farsiyar_classes').select('room_code').eq('room_code',code).maybeSingle();if(!data)return code}throw new Error('ساخت کد کلاس انجام نشد.')}
function subscribeTeacher(){if(!classRow)return;if(channel)supabase.removeChannel(channel);channel=supabase.channel('teacher:'+classRow.room_code).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_responses',filter:`room_code=eq.${classRow.room_code}`},payload=>{if(payload.eventType==='INSERT'){responses.unshift(payload.new);renderResponses();renderReport()}}).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_scores',filter:`room_code=eq.${classRow.room_code}`},()=>refreshScores()).on('broadcast',{event:'teacher-sync'},payload=>{}).subscribe(); roomChannel=supabase.channel('room:'+classRow.room_code).subscribe();}
async function refreshScores(){if(!classRow)return;const {data,error}=await supabase.from('farsiyar_scores').select('student_name,points').eq('room_code',classRow.room_code).order('points',{ascending:false}).order('student_name',{ascending:true});if(!error){scores=data||[];renderScores();renderReport()}}
async function loadResponses(){if(!classRow)return;const {data,error}=await supabase.from('farsiyar_responses').select('*').eq('room_code',classRow.room_code).order('created_at',{ascending:false}).limit(100);if(!error){responses=data||[];renderResponses();renderReport()}}
async function saveClass(patch,broadcast=true){if(!classRow)return;const {data,error}=await supabase.from('farsiyar_classes').update({...patch,updated_at:new Date().toISOString()}).eq('id',classRow.id).select('*').single();if(error){toast(errorText(error));return false}classRow=data;hydrateFromClass(data);if(broadcast)await broadcastState();return true}
async function broadcastState(){if(!classRow||!roomChannel)return;await roomChannel.send({type:'broadcast',event:'state',payload:{room_code:classRow.room_code,lesson_index:classRow.lesson_index,mission:classRow.mission,notice:classRow.notice,board_state:classRow.board_state}}).catch(()=>{});}
function renderLesson(){const i=Number($('lessonSelect').value||0),l=lessons[i];if(!l)return;const parts=l.parts.map(([n,p])=>`<a class="bookLink" target="_blank" rel="noopener" href="book/chaharom-farsi-1404.pdf#page=${p}">${esc(n)} • صفحه ${faNum(p)}</a>`).join('');$('lessonCard').innerHTML=`<div class="lessonCard"><div><span class="kicker" style="color:#8ed8d3">${esc(l.chapter)} • درس ${faNum(l.no)}</span><h3>${esc(l.title)}</h3><p>صفحه آغاز درس: ${faNum(l.page)} • ویدیوی آموزشی برای همین درس</p><div class="lessonMeta"><span class="chip">گام ۵ مرحله‌ای</span><span class="chip">مأموریت زنده</span><span class="chip">PDF مستقیم</span></div></div><div><a class="goldBtn" style="display:block;text-decoration:none;padding:11px 14px;border-radius:11px" target="_blank" rel="noopener" href="${esc(l.video)}">▶ ویدیوی درس</a></div></div>`;$('routeGrid').innerHTML=(routes[l.title]||[]).map((x,j)=>`<div class="routeStep"><b>مرحله ${faNum(j+1)}</b><strong>${esc(x)}</strong><small>${j===0?'ورود به موضوع':j===4?'جمع‌بندی و ارزشیابی':'تمرین مشارکتی و گفت‌وگو'}</small></div>`).join('');$('bookLinks').innerHTML=parts+`<a class="bookLink" target="_blank" href="book/chaharom-farsi-1404.pdf#page=140">نیایش • صفحه ۱۴۰</a><a class="bookLink" target="_blank" href="book/chaharom-farsi-1404.pdf#page=141">واژه‌نامه • صفحه ۱۴۱</a>`}
async function setLesson(){const i=Number($('lessonSelect').value);if(!classRow)return;await saveClass({lesson_index:i,mission:null,notice:''});renderMissionPreview();}
function renderMissionPreview(){const m=currentMission;if(!m){$('teacherMission').innerHTML='هنوز مأموریتی ارسال نشده است.';return}$('teacherMission').innerHTML=`<b>${esc(m.title)}</b><p>${esc(m.prompt)}</p>${m.options?.length?`<ul>${m.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ul>`:''}<small>نوع: ${esc(m.kind)} ${m.correct!==undefined?`• پاسخ صحیح: ${esc(m.correct)}`:''}</small>`}
function selectMission(type){selectedMissionType=type;document.querySelectorAll('[data-mission]').forEach(b=>b.classList.toggle('active',b.dataset.mission===type));const b=$('builder');if(type==='text')b.innerHTML=`<textarea id="mPrompt" placeholder="سؤال یا مأموریت نوشتاری…"></textarea><button class="primary" id="publishMission">ارسال به کلاس</button>`;if(type==='quiz')b.innerHTML=`<input id="mPrompt" placeholder="متن سؤال"><div class="optionRow"><input id="q0" placeholder="گزینه ۱"><input type="radio" name="correct" value="0" checked></div><div class="optionRow"><input id="q1" placeholder="گزینه ۲"><input type="radio" name="correct" value="1"></div><div class="optionRow"><input id="q2" placeholder="گزینه ۳"><input type="radio" name="correct" value="2"></div><div class="optionRow"><input id="q3" placeholder="گزینه ۴"><input type="radio" name="correct" value="3"></div><button class="primary" id="publishMission">ارسال آزمون</button>`;if(type==='dictation')b.innerHTML=`<textarea id="mPrompt" placeholder="جمله یا واژه‌ای که باید خوانده شود…"></textarea><input id="mAnswer" placeholder="پاسخ صحیح (برای تصحیح خودکار)"><button class="primary" id="publishMission">شروع املای صوتی</button>`;if(type==='sentence')b.innerHTML=`<input id="mPrompt" placeholder="واژه‌ها را با / جدا کن؛ مثال: دانش‌آموز / کتاب / خواند"><input id="mAnswer" placeholder="جمله صحیح یا یکی از پاسخ‌های پذیرفتنی"><button class="primary" id="publishMission">شروع جمله‌ساز</button>`;$('publishMission').onclick=publishMission}
async function publishMission(){if(!classRow){toast('اول کلاس بسازید.');return}const kind=selectedMissionType,prompt=$('mPrompt')?.value.trim();if(!prompt){toast('متن مأموریت را وارد کنید.');return}const m={id:crypto.randomUUID(),kind,title:kind==='text'?'پاسخ نوشتاری':kind==='quiz'?'چهارگزینه‌ای':kind==='dictation'?'املای صوتی':'جمله‌ساز',prompt,created_at:new Date().toISOString()};if(kind==='quiz'){m.options=[0,1,2,3].map(i=>$('q'+i).value.trim());if(m.options.some(x=>!x)){toast('هر چهار گزینه را کامل کنید.');return}m.correct=Number(document.querySelector('input[name=correct]:checked').value)}if(kind==='dictation'||kind==='sentence')m.answerKey=$('mAnswer').value.trim();if(kind==='sentence')m.words=prompt.split('/').map(x=>x.trim()).filter(Boolean);currentMission=m;await saveClass({mission:m});toast('مأموریت برای کلاس ارسال شد.')}
async function endMission(){if(!classRow)return;await saveClass({mission:null});toast('مأموریت پایان یافت.')}
async function sendNotice(){if(!classRow)return;const n=$('noticeInput').value.trim();await saveClass({notice:n});toast('پیام به کلاس ارسال شد.')}
async function copyLink(){if(!classRow)return;const url=`${location.origin}${location.pathname}?class=${classRow.room_code}`;await navigator.clipboard?.writeText(url);toast('لینک ورود کپی شد.')}
function renderRoster(){if(!$('rosterGrid'))return;$('rosterGrid').innerHTML=roster.map((n,i)=>`<div class="rosterItem"><span>${faNum(i+1)}</span><input data-roster="${i}" value="${esc(n)}" maxlength="80" placeholder="نام دانش‌آموز"></div>`).join('')}
async function saveRoster(){const arr=Array.from(document.querySelectorAll('[data-roster]')).map(x=>x.value.trim());const clean=arr.map(x=>x.replace(/\s+/g,' '));const non=clean.filter(Boolean);if(new Set(non).size!==non.length){toast('نام‌ها باید یکتا باشند.');return}roster=clean;if(!classRow){toast('ابتدا کلاس را بسازید.');return}if(non.length<1){toast('حداقل یک نام وارد کنید.');return}await saveClass({roster});toast('فهرست ۲۹ نفر ذخیره شد.')}
async function award(name,delta){try{const {data,error}=await supabase.rpc('award_farsiyar_points',{p_room_code:classRow.room_code,p_student_name:name,p_delta:delta});if(error)throw error;toast(`${name}: ${delta>0?'+':''}${delta} امتیاز`);await refreshScores();}catch(e){toast(errorText(e))}}
async function renderResponses(){if(!$('responses'))return;if(!responses.length){$('responses').innerHTML='<p class="muted">هنوز پاسخی ثبت نشده است.</p>';return}$('responses').innerHTML=responses.slice(0,60).map(r=>`<div class="responseItem"><b>${esc(r.student_name)}</b><small>${esc(r.kind)} • ${new Date(r.created_at).toLocaleTimeString('fa-IR')}</small><div>${esc(r.answer)}</div><small>${r.is_correct===true?'✓ درست':r.is_correct===false?'× نادرست':''}</small><div class="responseActions"><button onclick="window.__award('${encodeURIComponent(r.student_name)}',1)">+۱</button><button onclick="window.__award('${encodeURIComponent(r.student_name)}',2)">+۲</button><button onclick="window.__award('${encodeURIComponent(r.student_name)}',3)">+۳</button></div></div>`).join('')}
window.__award=(n,d)=>award(decodeURIComponent(n),d);
function renderScores(){if(!$('scoreBoard'))return;if(!scores.length){$('scoreBoard').innerHTML='<p class="muted">امتیازی ثبت نشده است.</p>';return}$('scoreBoard').innerHTML=scores.slice(0,29).map((s,i)=>`<div class="scoreRow"><span><i class="rank">${faNum(i+1)}</i>${esc(s.student_name)}</span><b>${faNum(s.points)}</b></div>`).join('')}
function renderReport(){if(!$('reportTable'))return;const map=new Map(scores.map(x=>[x.student_name,x.points]));const rows=roster.filter(Boolean).map(n=>`<tr><td>${esc(n)}</td><td>${faNum(map.get(n)||0)}</td><td>${faNum(responses.filter(r=>r.student_name===n).length)}</td></tr>`).join('');$('reportTable').innerHTML=`<div class="reportTable"><table><thead><tr><th>دانش‌آموز</th><th>امتیاز</th><th>تعداد پاسخ</th></tr></thead><tbody>${rows}</tbody></table></div>`}
async function clearScores(){if(!classRow)return;try{const {error}=await supabase.rpc('clear_farsiyar_scores',{p_room_code:classRow.room_code});if(error)throw error;scores=[];renderScores();renderReport();toast('تابلو امتیاز پاک شد.')}catch(e){toast(errorText(e))}}
function exportJson(){const payload={exported_at:new Date().toISOString(),class:classRow,responses,scores,roster};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`farsiyar-${classRow?.room_code||'class'}.json`;a.click();URL.revokeObjectURL(a.href)}
function printReport(){window.print()}
function renderBook(){const chapters={};lessons.forEach(l=>(chapters[l.chapter]??=[]).push(l));$('bookList').innerHTML=Object.entries(chapters).map(([ch,ls])=>`<article class="bookChapter"><h3>${esc(ch)}</h3><div class="bookLessons">${ls.map(l=>`<a class="bookLesson" target="_blank" rel="noopener" href="book/chaharom-farsi-1404.pdf#page=${l.page}"><b>درس ${faNum(l.no)}</b>${esc(l.title)} <small>صفحه ${faNum(l.page)}</small></a>`).join('')}</div></article>`).join('')+`<article class="bookChapter"><h3>بخش‌های پایانی کتاب</h3><div class="bookLessons"><a class="bookLesson" target="_blank" href="book/chaharom-farsi-1404.pdf#page=140">نیایش • ۱۴۰</a><a class="bookLesson" target="_blank" href="book/chaharom-farsi-1404.pdf#page=141">واژه‌نامه • ۱۴۱</a></div></article>`}

async function loadStudentNames(){const code=$('studentCode').value.trim().toUpperCase();$('studentError').textContent='';if(!/^FAR-\d{4}$/.test(code)){$('studentError').textContent='کد کلاس باید مثل FAR-1234 باشد.';return}if(!supabase){$('studentError').textContent='اتصال Supabase برقرار نیست.';return}$('studentName').innerHTML='<option>در حال دریافت…</option>';try{const {data,error}=await supabase.rpc('student_get_class',{p_room_code:code,p_student_name:'__roster_probe__'});if(error)throw error;if(!data?.length){/* roster intentionally not exposed by RPC; use public roster endpoint only through a separate safe function */const r=await supabase.rpc('student_get_roster',{p_room_code:code});if(r.error)throw r.error;populateNames(r.data||[])}else populateNames([])}catch(e){$('studentName').innerHTML='<option value="">فهرست پیدا نشد</option>';$('studentError').textContent=errorText(e)}}
function populateNames(data){$('studentName').innerHTML='<option value="">انتخاب نام…</option>'+data.map(x=>`<option value="${esc(x.student_name)}">${esc(x.student_name)}</option>`).join('')}
async function joinStudent(){const code=$('studentCode').value.trim().toUpperCase(),name=$('studentName').value.trim();$('studentError').textContent='';if(!/^FAR-\d{4}$/.test(code)){ $('studentError').textContent='کد کلاس نادرست است.';return}if(!name){$('studentError').textContent='نام خود را انتخاب کنید.';return}try{const {data,error}=await supabase.rpc('student_get_class',{p_room_code:code,p_student_name:name});if(error)throw error;if(!data?.length){$('studentError').textContent='این نام در فهرست کلاس ثبت نشده یا کلاس وجود ندارد.';return}const c=data[0];localStorage.setItem('farsiyar-student',JSON.stringify({code,name}));showStudentClass(c);subscribeStudent(code,name)}catch(e){$('studentError').textContent=errorText(e)}}
function showStudentClass(c){$('studentJoin').classList.add('hidden');$('studentApp').classList.remove('hidden');$('studentGreeting').textContent=`سلام ${JSON.parse(localStorage.getItem('farsiyar-student')).name}؛ آماده‌ای؟`;renderStudentState(c)}
function renderStudentState(c){const st=JSON.parse(localStorage.getItem('farsiyar-student')||'{}'),m=c.mission;$('studentNotice').textContent=c.notice||'';$('studentNotice').classList.toggle('show',!!c.notice);const l=lessons[c.lesson_index]||lessons[0];$('studentLesson').innerHTML=`<h3>درس ${faNum(l.no)}: ${esc(l.title)}</h3><p class="muted">صفحه ${faNum(l.page)}</p><a class="outline" target="_blank" href="book/chaharom-farsi-1404.pdf#page=${l.page}">باز کردن درس در کتاب</a> <a class="outline" target="_blank" href="${esc(l.video)}">ویدیوی آموزشی</a>`;$('studentMissionTitle').textContent=m?.title||'هنوز مأموریتی نیست';$('studentMissionBody').innerHTML=m?studentMissionHtml(m):'<p class="muted">وقتی معلم فعالیت را شروع کند اینجا نمایش داده می‌شود.</p>';loadStudentScores(st.code,st.name);drawBoard($('studentCanvas'),c.board_state||[])}
function studentMissionHtml(m){if(m.kind==='text')return`<p>${esc(m.prompt)}</p><div class="answerArea"><textarea id="sText" placeholder="پاسخت را بنویس…"></textarea><button class="primary wide" onclick="window.__submitStudent('text')">ارسال پاسخ</button></div>`;if(m.kind==='quiz')return`<p>${esc(m.prompt)}</p><div class="quizOptions">${m.options.map((o,i)=>`<button onclick="window.__quiz(${i})">${esc(o)}</button>`).join('')}</div><div id="quizFeedback"></div>`;if(m.kind==='dictation')return`<p>معلم متن را می‌خواند. بعد از گوش دادن، پاسخ را بنویس.</p><button class="goldBtn" onclick="window.__speak('${encodeURIComponent(m.prompt)}')">🔊 پخش صوت فارسی</button><div class="answerArea"><textarea id="sText" placeholder="آنچه شنیدی…"></textarea><button class="primary wide" onclick="window.__submitStudent('dictation')">ارسال املا</button></div>`;if(m.kind==='sentence')return`<p>کلمه‌ها را مرتب کن و یک جمله درست بساز:</p><div class="chips">${(m.words||[]).map(w=>`<button onclick="window.__word('${encodeURIComponent(w)}')">${esc(w)}</button>`).join(' ')}</div><input id="sentenceBuilt" style="width:100%;margin-top:10px;padding:11px;border:1px solid var(--line);border-radius:10px" placeholder="جمله‌ات را اینجا بساز"><button class="primary wide" style="margin-top:8px" onclick="window.__submitStudent('sentence')">ارسال جمله</button>`}
window.__speak=(txt)=>{if(!('speechSynthesis'in window)){toast('مرورگر از گفتار پشتیبانی نمی‌کند.');return}speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(decodeURIComponent(txt))) }
window.__word=w=>{const i=$('sentenceBuilt');i.value=(i.value+' '+decodeURIComponent(w)).trim()}
window.__quiz=async i=>{const st=JSON.parse(localStorage.getItem('farsiyar-student')||'{}'),m=currentMission||{};const correct=Number(m.correct)===i;document.querySelectorAll('.quizOptions button').forEach((b,j)=>b.disabled=true);$('quizFeedback').textContent=correct?'✓ درست!':'× این گزینه درست نیست.';await submitResponse(st.code,st.name,'quiz',m.options[i],correct)}
window.__submitStudent=kind=>{const st=JSON.parse(localStorage.getItem('farsiyar-student')||'{}'),v=$('sText')?.value.trim()||'';if(!v){toast('پاسخ را بنویس.');return}const m=currentMission||{};let correct=null;if(kind==='dictation')correct=normalize(v)===normalize(m.answerKey||'');submitResponse(st.code,st.name,kind,v,correct)}
async function submitResponse(code,name,kind,answer,isCorrect){try{const {error}=await supabase.from('farsiyar_responses').insert({room_code:code,student_name:name,kind,answer,is_correct:isCorrect,points_awarded:isCorrect===true?1:0});if(error)throw error;toast(isCorrect===true?'پاسخ درست ثبت شد ⭐':'پاسخ ثبت شد.');}catch(e){toast(errorText(e))}}
function normalize(x){return String(x||'').replace(/[\u200c\u200f\u200e\s]/g,'').replace(/[؟?!.،,؛;]/g,'').trim().toLowerCase()}
async function loadStudentScores(code,name){try{const {data,error}=await supabase.rpc('student_get_scores',{p_room_code:code,p_student_name:name});if(error)throw error;const rows=data||[];const me=rows.find(x=>x.student_name===name);$('myPoints').textContent=faNum(me?.points||0);$('studentScores').innerHTML=rows.slice(0,10).map((x,i)=>`<div class="scoreRow"><span><i class="rank">${faNum(i+1)}</i>${esc(x.student_name)}</span><b>${faNum(x.points)}</b></div>`).join('')||'<p class="muted">هنوز امتیازی ثبت نشده.</p>'}catch(e){$('studentScores').innerHTML='<p class="muted">تابلو امتیاز فعلاً در دسترس نیست.</p>'}}
async function subscribeStudent(code,name){if(studentChannel)supabase.removeChannel(studentChannel);studentChannel=supabase.channel('room:'+code).on('broadcast',{event:'state'},payload=>{if(payload.payload?.room_code!==code)return;const p=payload.payload;currentMission=p.mission;renderStudentState({lesson_index:p.lesson_index,mission:p.mission,notice:p.notice,board_state:p.board_state})}).subscribe();}
function initBoard(){const c=$('teacherCanvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle='#fffef9';ctx.fillRect(0,0,c.width,c.height);c.addEventListener('pointerdown',e=>{drawing=true;lastPoint=point(e,c);});c.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e,c);const stroke={x1:lastPoint.x,y1:lastPoint.y,x2:p.x,y2:p.y,color:$('boardMode').value==='eraser'?'#fffef9':$('boardColor').value,size:Number($('boardSize').value),mode:$('boardMode').value};boardState.push(stroke);lastPoint=p;drawBoard(c,boardState);syncBoardDebounced()});['pointerup','pointercancel','pointerleave'].forEach(ev=>c.addEventListener(ev,()=>{drawing=false;lastPoint=null}))}
function point(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
function drawBoard(c,state){const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fffef9';ctx.fillRect(0,0,c.width,c.height);ctx.lineCap='round';for(const s of state||[]){ctx.beginPath();ctx.moveTo(s.x1*c.width/1100,s.y1*c.height/560);ctx.lineTo(s.x2*c.width/1100,s.y2*c.height/560);ctx.strokeStyle=s.color||'#0b2a42';ctx.lineWidth=s.size||5;ctx.stroke()}}
let boardTimer;function syncBoardDebounced(){clearTimeout(boardTimer);boardTimer=setTimeout(()=>saveClass({board_state:boardState}),250)}
function undoBoard(){boardState.pop();drawBoard($('teacherCanvas'),boardState);syncBoardDebounced()}
function clearBoard(){boardState=[];drawBoard($('teacherCanvas'),boardState);syncBoardDebounced()}
let timerHandle=null;
function randomStudent(){const names=roster.filter(Boolean);if(!names.length){toast('ابتدا فهرست دانش‌آموزان را وارد کن.');return}const n=names[Math.floor(Math.random()*names.length)];$('quickToolOut').innerHTML=`<b>انتخاب شد:</b> ${esc(n)} ⭐`;toast(`نوبت ${n} است.`)}
function startTimer(){let left=60;clearInterval(timerHandle);$('quickToolOut').textContent=`زمان باقی‌مانده: ${faNum(left)} ثانیه`;timerHandle=setInterval(()=>{left--;if(left<=0){clearInterval(timerHandle);$('quickToolOut').textContent='⏰ زمان تمام شد.';toast('زمان فعالیت تمام شد.')}else $('quickToolOut').textContent=`زمان باقی‌مانده: ${faNum(left)} ثانیه`},1000)}
async function deleteClass(){if(!classRow||!confirm('کلاس فعلی و پاسخ‌های آن حذف شود؟'))return;try{const {error}=await supabase.from('farsiyar_classes').delete().eq('id',classRow.id);if(error)throw error;classRow=null;responses=[];scores=[];await createClass()}catch(e){toast(errorText(e))}}
function previewStudent(){if(!classRow){toast('ابتدا کلاس را بسازید.');return}showScreen('student');$('studentJoin').classList.add('hidden');$('studentApp').classList.remove('hidden');$('studentGreeting').textContent='پیش‌نمایش پنل دانش‌آموز برای معلم';renderStudentState(classRow)}
async function checkConnection(){try{const {error}=await supabase.from('farsiyar_classes').select('room_code').limit(1);if(error)throw error;$('supabaseInfo').textContent='اتصال برقرار است؛ دسترسی جدول کلاس پاسخ می‌دهد.';setConnection(true,'متصل')}catch(e){$('supabaseInfo').textContent=errorText(e);setConnection(false,'خطا')}}
function tabs(){document.querySelectorAll('.sideBtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sideBtn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='reports'){refreshScores();loadResponses();renderReport()}})}
function wire(){
 $('homeBtn').onclick=()=>showScreen('home');$('previewStudent').onclick=previewStudent;$('teacherBtn').onclick=()=>showScreen('teacher');$('studentBtn').onclick=()=>showScreen('student');$('heroTeacher').onclick=()=>showScreen('teacher');$('heroStudent').onclick=()=>showScreen('student');$('studentHome').onclick=()=>showScreen('home');$('loginBtn').onclick=signIn;$('teacherLogout').onclick=signOut;$('newClassBtn').onclick=createClass;$('lessonSelect').onchange=setLesson;$('sendNotice').onclick=sendNotice;$('endMission').onclick=endMission;$('copyLink').onclick=copyLink;$('saveRoster').onclick=saveRoster;$('exportJson').onclick=exportJson;$('printReport').onclick=printReport;$('deleteClass').onclick=deleteClass;$('randomStudent').onclick=randomStudent;$('timerBtn').onclick=startTimer;$('reconnect').onclick=checkConnection;$('undoBoard').onclick=undoBoard;$('clearBoard').onclick=clearBoard;$('loadNames').onclick=loadStudentNames;$('joinBtn').onclick=joinStudent;
 document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>selectMission(b.dataset.mission));tabs();selectMission('text');renderBook();$('lessonSelect').innerHTML=lessons.map((l,i)=>`<option value="${i}">درس ${faNum(l.no)} — ${esc(l.title)}</option>`).join('');initBoard();
 const q=new URLSearchParams(location.search).get('class');if(q){$('studentCode').value=q.toUpperCase();showScreen('student')}
}
window.addEventListener('online',()=>{if(supabase)setConnection(true,'آنلاین')});window.addEventListener('offline',()=>setConnection(false,'اینترنت قطع'));
wire();initSupabase();
})();
