const lessons=[
['فصل اول: آفرینش','۱','آفریدگار زیبایی'],['فصل اول: آفرینش','۲','کوچ پرستوها'],['فصل دوم: دانایی و هوشیاری','۳','راز نشانه‌ها'],['فصل دوم: دانایی و هوشیاری','۴','ارزش علم'],['فصل دوم: دانایی و هوشیاری','۵','رهایی از قفس'],['فصل سوم: ایران من','۶','آرش کمانگیر'],['فصل سوم: ایران من','۷','مهمان شهر ما'],['فصل چهارم: فرهنگ بومی','۸','درس آزاد'],['فصل چهارم: فرهنگ بومی','۹','درس آزاد'],['فصل پنجم: نام‌آوران','۱۰','باغچه اطفال'],['فصل پنجم: نام‌آوران','۱۱','فرمانده دل‌ها'],['فصل پنجم: نام‌آوران','۱۲','اتفاق ساده'],['فصل ششم: راه زندگی','۱۳','لطف حق'],['فصل ششم: راه زندگی','۱۴','ادب از که آموختی؟'],['فصل ششم: راه زندگی','۱۵','شیر و موش'],['فصل هفتم: علم و عمل','۱۶','پرسشگری'],['فصل هفتم: علم و عمل','۱۷','مدرسه هوشمند']];
const chapters={'فصل اول: آفرینش':['آفریدگار زیبایی','کوچ پرستوها'],'فصل دوم: دانایی و هوشیاری':['راز نشانه‌ها','ارزش علم','رهایی از قفس'],'فصل سوم: ایران من':['آرش کمانگیر','مهمان شهر ما'],'فصل چهارم: فرهنگ بومی':['درس آزاد','درس آزاد'],'فصل پنجم: نام‌آوران':['باغچه اطفال','فرمانده دل‌ها','اتفاق ساده'],'فصل ششم: راه زندگی':['لطف حق','ادب از که آموختی؟','شیر و موش'],'فصل هفتم: علم و عمل':['پرسشگری','مدرسه هوشمند']};
const lessonHints={'آفریدگار زیبایی':['مشاهده و گفت‌وگو درباره زیبایی‌های طبیعت','واژه‌آموزی و توصیف','درک مطلب و دلیل‌آوری','خوانش با لحن','نوشتن یک توصیف کوتاه'],'کوچ پرستوها':['پیش‌بینی موضوع','گوش دادن و بازگویی','واژه‌های دشوار','درک ترتیب رویدادها','نوشتن یک پیام برای پرستوها'],'راز نشانه‌ها':['بازی کارآگاه نشانه‌ها','حدس بر اساس نشانه‌ها','درست و نادرست','واژه‌های هم‌آوا','قصه‌گویی'],'ارزش علم':['پرسش آغازین','گفت‌وگوی سقراطی','واژه و جمله','درک مطلب','جمع‌بندی یک دقیقه‌ای'],'رهایی از قفس':['تصویرسازی ذهنی','پرسش‌های چرا','واژه‌های هم‌معنی','قصه‌گویی','پیام داستان'],'آرش کمانگیر':['نقشه داستان','شخصیت و هدف','واژه‌های حماسی','خوانش آهنگین','ساخت پایان جایگزین'],'مهمان شهر ما':['معرفی شهر','نشانه‌های فرهنگی','مصاحبه کلاسی','واژه‌سازی','نامه به یک مهمان'],'درس آزاد':['محتوای بومی کلاس','جمع‌آوری واژه‌های محلی','قصه یا خاطره','ارائه دانش‌آموز','ساخت صفحه مجله کلاس'],'باغچه اطفال':['مشاهده شخصیت‌ها','نقش‌آفرینی','واژه‌آموزی','سؤال از متن','یک پاراگراف خلاق'],'فرمانده دل‌ها':['شناخت شخصیت','ویژگی‌های اخلاقی','گفت‌وگو','درک مطلب','نوشتن یک پیام'],'اتفاق ساده':['پیش‌بینی','علت و معلول','واژه‌آموزی','قصه‌گویی','بازنویسی'],'لطف حق':['خوانش شعر','معنی واژه‌ها','پیام شعر','تکمیل مصراع','بازگویی مفهوم'],'ادب از که آموختی؟':['نقش‌آفرینی','موقعیت‌های واقعی','واژه و جمله','درک پیام','یک قانون طلایی ادب'],'شیر و موش':['نقش‌آفرینی داستان','ترتیب رویدادها','مترادف و متضاد','پایان دیگر','پیام داستان'],'پرسشگری':['ساخت سؤال خوب','کارآگاه سؤال','طبقه‌بندی سؤال‌ها','گفت‌وگوی گروهی','ثبت یک پرسش تازه'],'مدرسه هوشمند':['ایده‌پردازی','فناوری و یادگیری','واژه‌های مرتبط','طراحی کلاس آینده','ارائه کوتاه']};
const tools=[['warm','🔥','شروع جذاب'],['word','🔤','آزمایشگاه واژه'],['dict','✏️','املای هوشمند'],['comprehend','🧠','درک مطلب'],['poem','🎵','شعر را کامل کن'],['story','🎭','صندلی قصه‌گویی'],['sentence','🧩','جمله‌ساز'],['quiz','🎯','مسابقه چهارگزینه‌ای'],['spin','🎲','گردونه کلاس'],['timer','⏱️','زمان‌سنج'],['notice','📢','پیام معلم'],['book','📖','نمایش کتاب']];
const blankRoster=()=>Array.from({length:29},(_,i)=>`دانش‌آموز ${i+1}`);
const defaultState={classCode:'FAR-4821',lesson:0,mission:null,responses:[],scores:{},notice:'',teacher:false,roster:blankRoster()};
let S=JSON.parse(localStorage.getItem('farsiyar-pro')||'null')||defaultState;
S.roster=Array.isArray(S.roster)?S.roster.slice(0,29).concat(Array(Math.max(0,29-S.roster.length)).fill('')).slice(0,29):blankRoster();
S.scores=S.scores||{}; S.responses=S.responses||[];
function save(){localStorage.setItem('farsiyar-pro',JSON.stringify(S))}
const originalSave=save;
function toast(x){const t=document.getElementById('toast');if(!t)return;t.textContent=x;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const e=document.getElementById(id);if(e)e.classList.add('active');scrollTo(0,0)}
function openTeacher(){go('teacher')} function openBook(){go('book')}
function loginTeacher(){if(document.getElementById('teacherPass').value==='19121912'){S.teacher=true;originalSave();showTeacher();toast('به اتاق فرمان خوش آمدی 👩‍🏫')}else toast('رمز اشتباه است')}
function showTeacher(){document.getElementById('teacherLogin').classList.add('hidden');document.getElementById('teacherPanel').classList.remove('hidden');document.getElementById('classCode').textContent=S.classCode;document.getElementById('lessonSelect').value=S.lesson;updateLesson();renderScores();renderResponses();renderRoster()}
async function newClass(){await createCloudClass()}
function updateLesson(){const el=document.getElementById('lessonSelect');if(!el)return;const i=+el.value;S.lesson=i;originalSave();const [ch,n,title]=lessons[i];document.getElementById('lessonInfo').innerHTML=`<span class="eyebrow">${ch} • درس ${n}</span><h3>${title}</h3><p>این درس را با مسیر پیشنهادی اجرا کن؛ هر مرحله را می‌توانی به ابزار زنده تبدیل کنی.</p>`;document.getElementById('route').innerHTML=(lessonHints[title]||[]).map((x,j)=>`<div class="step"><span>${['🎬','🔎','🧩','🎤','✍️'][j]}</span><b>مرحله ${j+1}</b><small>${x}</small></div>`).join('');renderTools();if(cloudReady&&S.teacher)cloudUpdateClass({lesson_index:S.lesson})}
function renderTools(){document.getElementById('toolCards').innerHTML=tools.map(t=>`<div class="toolCard" onclick="tool('${t[0]}')"><div class="ico">${t[1]}</div><b>${t[2]}</b></div>`).join('')}
function tool(type){const title=lessons[S.lesson][2],a=document.getElementById('toolArea');
if(type==='warm')a.innerHTML=`<h3>🔥 شروع جذاب: ${title}</h3><div class="questionBox">اگر تو معلم بودی، قبل از خواندن این درس چه سؤالی از بچه‌ها می‌پرسیدی تا کنجکاو شوند؟</div><div class="row"><button class="primary" onclick="startCustom('پرسش آغازین','هر دانش‌آموز یک حدس یا سؤال جذاب بنویسد.')">ارسال به کلاس</button><button onclick="randomPrompt()">🎲 سؤال تصادفی</button></div><p id="randomOut"></p>`;
if(type==='word')a.innerHTML=`<h3>🔤 آزمایشگاه واژه</h3><p>واژه را وارد کن تا کلاس درباره معنی، هم‌خانواده یا مترادف آن فعالیت کند.</p><input id="wordInput" placeholder="مثلاً: دانش، تلاش، شگفتی"><div class="row"><button class="primary" onclick="wordMission('معنی و کاربرد')">معنی و کاربرد</button><button onclick="wordMission('مترادف و متضاد')">مترادف/متضاد</button><button onclick="wordMission('جمله‌سازی')">جمله‌سازی</button></div>`;
if(type==='dict')a.innerHTML=`<h3>✏️ املای هوشمند</h3><p>معلم یک واژه یا جمله را وارد کند؛ سپس آن را به مأموریت کلاسی تبدیل کن.</p><textarea id="dictInput" placeholder="جمله یا واژه‌های املا..."></textarea><button class="primary" onclick="startCustom('املای کلاس',document.getElementById('dictInput').value)">شروع املا</button>`;
if(type==='comprehend')a.innerHTML=`<h3>🧠 درک مطلب</h3><p>یک سؤال متنی برای گفت‌وگوی کلاسی بساز.</p><textarea id="compInput" placeholder="سؤال درک مطلب..."></textarea><button class="primary" onclick="startCustom('درک مطلب',document.getElementById('compInput').value)">پرسش از کلاس</button>`;
if(type==='poem')a.innerHTML=`<h3>🎵 شعر را کامل کن</h3><p>بخش ناقص شعر/مصراع را خودت وارد کن تا دانش‌آموزان ادامه را حدس بزنند.</p><textarea id="poemInput" placeholder="بخش شعر یا مصراع ناقص..."></textarea><input id="poemKey" placeholder="پاسخ/ادامه صحیح (اختیاری)"><button class="primary" onclick="startCustom('شعر را کامل کن',document.getElementById('poemInput').value,document.getElementById('poemKey').value)">شروع مسابقه</button>`;
if(type==='story')a.innerHTML=`<h3>🎭 صندلی قصه‌گویی</h3><p>دانش‌آموز باید داستان را با لحن و ترتیب رویدادها ادامه دهد.</p><input id="storyPrompt" placeholder="شروع داستان..."><button class="primary" onclick="startCustom('صندلی قصه‌گویی',document.getElementById('storyPrompt').value)">صندلی را آماده کن</button>`;
if(type==='sentence')a.innerHTML=`<h3>🧩 جمله‌ساز</h3><p>واژه‌ها را وارد کن تا دانش‌آموزان از آن‌ها جمله بسازند.</p><input id="sentInput" placeholder="مثلاً: دانش‌آموز / کتاب / خواند"><button class="primary" onclick="startCustom('جمله‌سازی',document.getElementById('sentInput').value)">ارسال به کلاس</button>`;
if(type==='quiz')a.innerHTML=`<h3>🎯 مسابقه چهارگزینه‌ای</h3><input id="qInput" placeholder="سؤال"><input id="q1" placeholder="گزینه ۱"><input id="q2" placeholder="گزینه ۲"><input id="q3" placeholder="گزینه ۳"><input id="q4" placeholder="گزینه ۴"><select id="correct"><option value="1">پاسخ ۱</option><option value="2">پاسخ ۲</option><option value="3">پاسخ ۳</option><option value="4">پاسخ ۴</option></select><button class="primary" onclick="quizMission()">شروع مسابقه</button>`;
if(type==='spin')a.innerHTML=`<h3>🎲 گردونه کلاس</h3><p>برای مشارکت تصادفی یک مأموریت انتخاب کن.</p><button class="primary" onclick="spin()">چرخاندن گردونه 🎲</button><div id="spinOut" class="questionBox">آماده‌ای؟</div>`;
if(type==='timer')a.innerHTML=`<h3>⏱️ زمان‌سنج فعالیت</h3><input id="mins" type="number" min="1" max="60" value="3"><button class="primary" onclick="runTimer()">شروع</button><div id="clock" class="questionBox">03:00</div>`;
if(type==='notice')a.innerHTML=`<h3>📢 پیام معلم</h3><textarea id="noticeInput" placeholder="مثلاً: تا دو دقیقه دیگر پاسخ‌ها را ارسال کنید.">${escapeHtml(S.notice)}</textarea><button class="primary" onclick="sendNotice()">نمایش برای کلاس</button>`;
if(type==='book')a.innerHTML=`<h3>📖 کتاب فارسی چهارم</h3><p>کتاب فارسی چهارم ۱۴۰۴ داخل پروژه قرار گرفته است.</p><a class="pdfBtn" href="book/chaharom-farsi-1404.pdf" target="_blank">باز کردن کتاب</a>`;
}
function startCustom(kind,prompt,key=''){if(!prompt){toast('متن فعالیت را وارد کن');return}S.mission={kind,prompt,key,lesson:lessons[S.lesson][2],at:Date.now()};originalSave();if(cloudReady)cloudUpdateClass({lesson_index:S.lesson,mission:S.mission});renderMission();toast(cloudReady?'مأموریت برای همه گوشی‌ها ارسال شد 🚀':'مأموریت آماده شد 🚀')}
function wordMission(mode){const w=document.getElementById('wordInput').value.trim();if(!w){toast('یک واژه وارد کن');return}startCustom(mode,`واژه «${w}» را بررسی کن و ${mode} را انجام بده.`)}
function quizMission(){const q=document.getElementById('qInput').value.trim(),opts=[1,2,3,4].map(i=>document.getElementById('q'+i).value.trim());if(!q||opts.some(x=>!x)){toast('سؤال و هر چهار گزینه را کامل کن');return}startCustom('مسابقه چهارگزینه‌ای',JSON.stringify({q,opts}),document.getElementById('correct').value)}
function renderMission(){const m=S.mission,e=document.getElementById('missionBox');if(e)e.innerHTML=m?`<b>${escapeHtml(m.kind)}</b><p>${formatMission(m,true)}</p><small>درس: ${escapeHtml(m.lesson)}</small>`:'هنوز فعالیتی شروع نشده.';renderStudentMission();renderNoticeIfNeeded()}
function formatMission(m,teacher=false){if(m.kind==='مسابقه چهارگزینه‌ای'){let x;try{x=JSON.parse(m.prompt)}catch{return escapeHtml(m.prompt)}return `<div class="questionBox"><b>${escapeHtml(x.q)}</b>${teacher?'':`<div class="options">${x.opts.map((o,i)=>`<button type="button" onclick="answerQuiz(${i+1})">${i+1}) ${escapeHtml(o)}</button>`).join('')}</div>`}</div>`}return escapeHtml(m.prompt)}
async function answerQuiz(choice){const n=localStorage.getItem('studentName')||'دانش‌آموز';if(!S.mission||S.mission.kind!=='مسابقه چهارگزینه‌ای'){toast('مسابقه فعالی وجود ندارد');return}let x;try{x=JSON.parse(S.mission.prompt)}catch{return}const correct=String(S.mission.key||''),ok=String(choice)===correct,text=ok?`گزینه ${choice} را انتخاب کرد؛ پاسخ درست بود.`:`گزینه ${choice} را انتخاب کرد.`;await submitResponse(n,'مسابقه چهارگزینه‌ای',text,ok?2:1);toast(ok?'آفرین! پاسخ درست بود ⭐':'پاسخت ثبت شد')}
function startMission(){if(!S.mission)startCustom('فعالیت فوری',`هر دانش‌آموز درباره «${lessons[S.lesson][2]}» یک نکته، سؤال یا برداشت خود را بنویسد.`);else toast('مأموریت فعلی فعال است')}
async function stopMission(){S.mission=null;originalSave();if(cloudReady)await cloudUpdateClass({mission:null});renderMission();toast('مأموریت پایان یافت')}
function renderResponses(){const r=document.getElementById('responses');if(!r)return;r.innerHTML=S.responses.length?S.responses.slice().reverse().map(x=>`<div class="response"><b>${escapeHtml(x.name)}</b><small> • ${escapeHtml(x.kind)}</small><p>${escapeHtml(x.answer)}</p></div>`).join(''):'هنوز پاسخی ثبت نشده.'}
function normalizeName(n){return n.replace(/\s+/g,' ').trim()}
function renderRoster(){const box=document.getElementById('roster');if(!box)return;box.innerHTML=S.roster.map((name,i)=>`<div class="rosterRow"><span>${i+1}</span><input id="student-${i}" value="${escapeHtml(name)}" placeholder="نام دانش‌آموز ${i+1}"></div>`).join('')}
async function saveRoster(){const names=S.roster.map((_,i)=>normalizeName(document.getElementById(`student-${i}`).value));const nonEmpty=names.filter(Boolean);if(new Set(nonEmpty).size!==nonEmpty.length){toast('نام دانش‌آموزان نباید تکراری باشد');return}S.roster=names;names.forEach(n=>{if(n&&!Number.isFinite(S.scores[n]))S.scores[n]=0});originalSave();if(cloudReady)await cloudUpdateClass({roster:S.roster});renderScores();toast(`فهرست ${nonEmpty.length} دانش‌آموز ذخیره شد ✅`)}
function resetRoster(){S.roster=blankRoster();S.scores={};originalSave();renderRoster();renderScores();if(cloudReady)cloudUpdateClass({roster:S.roster});toast('فهرست پاک شد')}
function renderScores(){const e=document.getElementById('scoreTable');if(!e)return;const names=S.roster.filter(Boolean);const extras=Object.keys(S.scores).filter(n=>!names.includes(n));const all=[...names,...extras];const arr=all.map(n=>[n,Number(S.scores[n]||0)]).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'fa'));e.innerHTML=arr.length?`<div class="scoreRow"><b>دانش‌آموز</b><b>امتیاز</b><b>رتبه</b></div>`+arr.map((x,i)=>`<div class="scoreRow"><span>${escapeHtml(x[0])}</span><b>${x[1]} ⭐</b><span>${i+1}</span></div>`).join(''):'ابتدا نام دانش‌آموزان را در مدیریت کلاس وارد کن.'}
async function clearScores(){S.scores={};S.roster.filter(Boolean).forEach(n=>S.scores[n]=0);originalSave();if(cloudReady)await cloudResetScores();renderScores();toast('امتیازها صفر شد')}
function randomPrompt(){const p=['اگر عنوان درس را عوض می‌کردی چه می‌گذاشتی؟','کدام واژهٔ درس برایت جالب‌تر است و چرا؟','اگر جای شخصیت اصلی بودی چه می‌کردی؟','از این درس چه چیزی می‌توانی در زندگی واقعی استفاده کنی؟'];document.getElementById('randomOut').textContent=p[Math.floor(Math.random()*p.length)]}
function spin(){const x=['یک سؤال بساز','یک واژه را توضیح بده','یک جمله بساز','داستان را ادامه بده','پیام درس را بگو','یک نفر را برای قصه‌گویی انتخاب کن'];document.getElementById('spinOut').textContent=x[Math.floor(Math.random()*x.length)]}
let timer;function runTimer(){clearInterval(timer);let sec=Math.max(60,Math.min(3600,(+document.getElementById('mins').value||3)*60)),el=document.getElementById('clock');const tick=()=>{el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};tick();timer=setInterval(()=>{sec--;tick();if(sec<=0){clearInterval(timer);toast('زمان فعالیت تمام شد ⏰')}},1000)}
function sendNotice(){S.notice=document.getElementById('noticeInput').value.trim();originalSave();if(cloudReady)cloudUpdateClass({notice:S.notice});renderNoticeIfNeeded();toast(cloudReady?'پیام برای همه گوشی‌ها ارسال شد 📢':'پیام ثبت شد 📢')}
function renderNoticeIfNeeded(){const n=document.getElementById('studentNotice');if(n)n.textContent=S.notice?`📢 پیام معلم: ${S.notice}`:''}
function exportData(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='farsiyar-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printReport(){const w=open('','_blank');if(!w){toast('پنجره چاپ توسط مرورگر مسدود شد');return}w.document.write(`<html dir="rtl"><body style="font-family:tahoma;padding:30px"><h1>گزارش جلسه فارسی‌یار</h1><p>درس: ${escapeHtml(lessons[S.lesson][2])}</p><p>کد کلاس: ${escapeHtml(S.classCode)}</p><h2>دانش‌آموزان</h2>${S.roster.filter(Boolean).map((n,i)=>`<p>${i+1}. ${escapeHtml(n)} — ${Number(S.scores[n]||0)} امتیاز</p>`).join('')}<h2>پاسخ‌ها</h2>${S.responses.map(x=>`<p><b>${escapeHtml(x.name)}</b>: ${escapeHtml(x.answer)}</p>`).join('')}</body></html>`);w.document.close();w.focus();w.print()}
function resetAll(){if(confirm('همه داده‌های محلی پاک شود؟')){localStorage.removeItem('farsiyar-pro');localStorage.removeItem('farsiyar-room');localStorage.removeItem('studentName');location.reload()}}
let canvas,ctx,drawing=false;function initBoard(){canvas=document.getElementById('canvas');if(!canvas)return;ctx=canvas.getContext('2d');canvas.addEventListener('pointerdown',e=>{drawing=true;ctx.beginPath();ctx.moveTo(...pos(e))});canvas.addEventListener('pointermove',e=>{if(!drawing)return;ctx.lineWidth=+document.getElementById('penSize').value;ctx.lineCap='round';ctx.lineTo(...pos(e));ctx.stroke()});['pointerup','pointerleave'].forEach(e=>canvas.addEventListener(e,()=>drawing=false))}function clearBoard(){if(ctx)ctx.clearRect(0,0,canvas.width,canvas.height)}function pos(e){const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height]}
function escapeHtml(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}

// ===== Supabase multi-device sync =====
let cloud=null,realtime=null,cloudReady=false,cloudError='';
function cloudStatus(msg){const el=document.getElementById('cloudStatus');if(el)el.textContent=msg}
function cloudConfigured(){return !!(window.FARSYAR_SUPABASE_URL&&window.FARSYAR_SUPABASE_ANON_KEY)}
async function initCloud(){if(!cloudConfigured()){cloudStatus('آفلاین • ابزارهای کلاس فعال هستند');return false}if(!window.supabase){cloudStatus('آفلاین • کتابخانه ابری بارگذاری نشد');return false}try{cloud=window.supabase.createClient(window.FARSYAR_SUPABASE_URL,window.FARSYAR_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const {error}=await cloud.from('farsiyar_classes').select('room_code').limit(1);if(error){cloudError=error.message||String(error);cloudStatus('آفلاین • خطای دسترسی Supabase');return false}cloudReady=true;cloudStatus('آنلاین • Supabase متصل است 🌐');return true}catch(e){cloudError=e?.message||String(e);cloudStatus('آفلاین • اتصال ابری برقرار نشد');return false}}
async function createCloudClass(){const code='FAR-'+Math.floor(1000+Math.random()*9000);if(!cloudReady){S.classCode=code;S.responses=[];S.scores={};S.mission=null;S.notice='';originalSave();document.getElementById('classCode').textContent=code;renderScores();renderRoster();toast('کد کلاس آفلاین ساخته شد');return true}const {error}=await cloud.from('farsiyar_classes').insert({room_code:code,title:'کلاس فارسی چهارم',lesson_index:S.lesson,mission:null,notice:'',roster:S.roster});if(error){console.error(error);cloudReady=false;cloudStatus('آفلاین • ساخت کلاس آنلاین ناموفق بود');return createCloudClass()}S.classCode=code;S.responses=[];S.scores={};S.roster=Array.isArray(S.roster)?S.roster:blankRoster();S.roster.filter(Boolean).forEach(n=>S.scores[n]=0);originalSave();document.getElementById('classCode').textContent=code;subscribeRoom(code);renderScores();toast('کلاس آنلاین جدید ساخته شد 🌐');return true}
async function loadCloudClass(code){if(!cloudReady)return null;const {data,error}=await cloud.from('farsiyar_classes').select('*').eq('room_code',code).maybeSingle();if(error||!data)return null;S.classCode=code;S.lesson=Number.isInteger(data.lesson_index)?data.lesson_index:0;S.mission=data.mission||null;S.notice=data.notice||'';S.roster=Array.isArray(data.roster)?data.roster.slice(0,29).concat(Array(Math.max(0,29-(data.roster||[]).length)).fill('')).slice(0,29):blankRoster();const [rr,ss]=await Promise.all([cloud.from('farsiyar_responses').select('*').eq('room_code',code).order('created_at',{ascending:true}),cloud.from('farsiyar_scores').select('*').eq('room_code',code)]);if(rr.error||ss.error){toast('دریافت اطلاعات کلاس کامل نشد');return null}S.responses=(rr.data||[]).map(x=>({id:x.id,name:x.student_name,kind:x.kind,answer:x.answer,time:new Date(x.created_at).toLocaleString('fa-IR')}));S.scores={};(ss.data||[]).forEach(x=>S.scores[x.student_name]=x.points);S.roster.filter(Boolean).forEach(n=>{if(!Number.isFinite(S.scores[n]))S.scores[n]=0});originalSave();document.getElementById('classCode').textContent=code;document.getElementById('lessonSelect').value=S.lesson;updateLesson();renderRoster();renderScores();renderMission();subscribeRoom(code);return data}
function subscribeRoom(code){if(!cloudReady)return;if(realtime)cloud.removeChannel(realtime);realtime=cloud.channel('farsiyar-room-'+code).on('postgres_changes',{event:'UPDATE',schema:'public',table:'farsiyar_classes',filter:`room_code=eq.${code}`},payload=>{const x=payload.new||{};S.lesson=x.lesson_index??S.lesson;S.mission=x.mission||null;S.notice=x.notice||'';if(Array.isArray(x.roster))S.roster=x.roster.slice(0,29).concat(Array(Math.max(0,29-x.roster.length)).fill('')).slice(0,29);S.roster.filter(Boolean).forEach(n=>{if(!Number.isFinite(S.scores[n]))S.scores[n]=0});originalSave();if(document.getElementById('lessonSelect'))document.getElementById('lessonSelect').value=S.lesson;renderMission();renderRoster();renderScores();}).on('postgres_changes',{event:'INSERT',schema:'public',table:'farsiyar_responses',filter:`room_code=eq.${code}`},payload=>{const x=payload.new;if(!S.responses.some(r=>r.id===x.id)){S.responses.push({id:x.id,name:x.student_name,kind:x.kind,answer:x.answer,time:new Date(x.created_at).toLocaleString('fa-IR')});originalSave();renderResponses()}}).on('postgres_changes',{event:'*',schema:'public',table:'farsiyar_scores',filter:`room_code=eq.${code}`},payload=>{const x=payload.new||payload.old;if(x?.student_name){S.scores[x.student_name]=Number(x.points||0);originalSave();renderScores()}}).subscribe();}
async function cloudUpdateClass(patch){if(!cloudReady)return false;const {error}=await cloud.from('farsiyar_classes').update(patch).eq('room_code',S.classCode);if(error){console.error(error);toast('ذخیره آنلاین انجام نشد');return false}return true}
async function cloudAddResponse(name,kind,answer,delta=1){if(!cloudReady)return null;const {data,error}=await cloud.from('farsiyar_responses').insert({room_code:S.classCode,student_name:name,kind,answer}).select('id,student_name,kind,answer,created_at').single();if(error){console.error(error);toast('ارسال پاسخ آنلاین ناموفق بود؛ پاسخ محلی ثبت شد');return null}const {data:points,error:scoreError}=await cloud.rpc('increment_farsiyar_score',{p_room_code:S.classCode,p_student_name:name,p_delta:delta});if(scoreError)console.warn('score RPC failed',scoreError);return {row:data,points:Number(points??(S.scores[name]||0)+delta)}}
async function cloudResetScores(){if(!cloudReady)return;await cloud.from('farsiyar_scores').update({points:0,updated_at:new Date().toISOString()}).eq('room_code',S.classCode)}
async function submitResponse(name,kind,answer,delta=1){if(cloudReady){const result=await cloudAddResponse(name,kind,answer,delta);if(result){S.responses.push({id:result.row.id,name:result.row.student_name,kind:result.row.kind,answer:result.row.answer,time:new Date(result.row.created_at).toLocaleString('fa-IR')});S.scores[name]=result.points;originalSave();renderResponses();renderScores();return true}}S.responses.push({id:'local-'+Date.now()+'-'+Math.random(),name,kind,answer,time:new Date().toLocaleString('fa-IR')});S.scores[name]=(S.scores[name]||0)+delta;originalSave();renderResponses();renderScores();return false}

async function joinStudent(){const n=normalizeName(document.getElementById('studentName').value),c=document.getElementById('studentCode').value.trim().toUpperCase();if(!n||!c){toast('نام و کد کلاس را وارد کن');return}if(cloudReady){const data=await loadCloudClass(c);if(!data){toast('کد کلاس پیدا نشد');return}}else if(c!==S.classCode){toast('در حالت آفلاین، کد باید با کلاس همین دستگاه یکی باشد');return}const roster=S.roster.filter(Boolean);if(roster.length&& !roster.includes(n)){toast('این نام در فهرست ۲۹ دانش‌آموز کلاس ثبت نشده است');return}localStorage.setItem('studentName',n);localStorage.setItem('farsiyar-room',c);document.querySelector('.studentJoin').classList.add('hidden');document.getElementById('studentRoom').classList.remove('hidden');document.getElementById('studentWelcome').textContent=`سلام ${n} 👋 آماده‌ای؟`;renderStudentMission();toast('با موفقیت وارد کلاس شدی 🌐')}
async function submitStudentAnswer(){const a=document.getElementById('studentAnswer').value.trim(),n=localStorage.getItem('studentName')||'دانش‌آموز';if(!a||!S.mission){toast('اول مأموریت فعال باشد و پاسخ را بنویس');return}await submitResponse(n,S.mission.kind,a,1);document.getElementById('studentAnswer').value='';toast('پاسخ برای معلم ثبت شد ⭐')}

// UI init
(function initUI(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabPage').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active');if(b.dataset.tab==='scores')renderScores();if(b.dataset.tab==='live'){renderMission();renderResponses()}});document.getElementById('teacherBtn').onclick=openTeacher;document.getElementById('studentBtn').onclick=()=>go('student');const ls=document.getElementById('lessonSelect');ls.innerHTML=lessons.map((x,i)=>`<option value="${i}">درس ${x[1]} — ${x[2]}</option>`).join('');ls.value=S.lesson;ls.onchange=updateLesson;document.getElementById('chapters').innerHTML=Object.entries(chapters).map(([c,l])=>`<article class="chapter"><h3>${c}</h3><div class="lessonList">${l.map(x=>`<span class="lessonChip">${x}</span>`).join('')}</div></article>`).join('');initBoard();if(S.teacher)showTeacher();else updateLesson();renderStudentMission();setInterval(()=>{if(!document.getElementById('teacherPanel')?.classList.contains('hidden')){renderMission();renderResponses();}},1500)})()

(async()=>{const ok=await initCloud();if(ok){document.documentElement.dataset.cloud='on';const room=localStorage.getItem('farsiyar-room');if(room&&!S.teacher)await loadCloudClass(room);if(S.teacher){const existing=await loadCloudClass(S.classCode);if(!existing)await createCloudClass()}}})();
