-- فارسی‌یار | ساختار کامل برای دیتابیس تازه
-- اگر جدول‌های قدیمی دارید، به‌جای اجرای مجدد این فایل از supabase-migrate-existing.sql استفاده کنید.
create extension if not exists pgcrypto;

create table if not exists public.farsiyar_classes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  room_code text not null unique check (room_code ~ '^FAR-[0-9]{4}$'),
  title text not null default 'کلاس فارسی چهارم',
  roster jsonb not null default '[]'::jsonb check (jsonb_typeof(roster) = 'array'),
  lesson_index integer not null default 0 check (lesson_index between 0 and 16),
  mission jsonb not null default '{}'::jsonb,
  notice text not null default '',
  board_state jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.farsiyar_responses (
  id bigint generated by default as identity primary key,
  room_code text not null references public.farsiyar_classes(room_code) on delete cascade,
  student_name text not null check (length(trim(student_name)) between 1 and 80),
  kind text not null check (kind in ('text','quiz','dictation','sentence')),
  answer text not null,
  is_correct boolean,
  points_awarded integer not null default 0 check (points_awarded between 0 and 3),
  created_at timestamptz not null default now()
);
create table if not exists public.farsiyar_scores (
  id bigint generated by default as identity primary key,
  room_code text not null references public.farsiyar_classes(room_code) on delete cascade,
  student_name text not null,
  points integer not null default 0 check (points >= 0),
  updated_at timestamptz not null default now(),
  unique(room_code, student_name)
);

alter table public.farsiyar_classes enable row level security;
alter table public.farsiyar_responses enable row level security;
alter table public.farsiyar_scores enable row level security;

drop policy if exists classes_owner_select on public.farsiyar_classes;
create policy classes_owner_select on public.farsiyar_classes for select to authenticated using (owner_id = auth.uid());
drop policy if exists classes_owner_insert on public.farsiyar_classes;
create policy classes_owner_insert on public.farsiyar_classes for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists classes_owner_update on public.farsiyar_classes;
create policy classes_owner_update on public.farsiyar_classes for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists classes_owner_delete on public.farsiyar_classes;
create policy classes_owner_delete on public.farsiyar_classes for delete to authenticated using (owner_id = auth.uid());

drop policy if exists responses_student_insert on public.farsiyar_responses;
create policy responses_student_insert on public.farsiyar_responses for insert to anon, authenticated with check (
  points_awarded = 0 and exists (
    select 1 from public.farsiyar_classes c where c.room_code = farsiyar_responses.room_code
      and c.roster @> jsonb_build_array(farsiyar_responses.student_name)
  )
);
drop policy if exists responses_owner_select on public.farsiyar_responses;
create policy responses_owner_select on public.farsiyar_responses for select to authenticated using (
  exists (select 1 from public.farsiyar_classes c where c.room_code = farsiyar_responses.room_code and c.owner_id = auth.uid())
);
drop policy if exists responses_owner_delete on public.farsiyar_responses;
create policy responses_owner_delete on public.farsiyar_responses for delete to authenticated using (
  exists (select 1 from public.farsiyar_classes c where c.room_code = farsiyar_responses.room_code and c.owner_id = auth.uid())
);
drop policy if exists scores_owner_select on public.farsiyar_scores;
create policy scores_owner_select on public.farsiyar_scores for select to authenticated using (
  exists (select 1 from public.farsiyar_classes c where c.room_code = farsiyar_scores.room_code and c.owner_id = auth.uid())
);

create or replace function public.create_farsiyar_class()
returns public.farsiyar_classes language plpgsql security invoker set search_path = public as $$
declare v_user uuid := auth.uid(); v_code text; v_row public.farsiyar_classes; v_try integer := 0;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  loop
    v_try := v_try + 1;
    v_code := 'FAR-' || lpad(floor(random() * 10000)::integer::text, 4, '0');
    begin
      insert into public.farsiyar_classes(owner_id,room_code,title,lesson_index,roster,mission,notice,board_state)
      values(v_user,v_code,'کلاس فارسی چهارم',0,'[]'::jsonb,'{}'::jsonb,'','[]'::jsonb) returning * into v_row;
      return v_row;
    exception when unique_violation then
      if v_try >= 30 then raise exception 'ROOM_CODE_EXHAUSTED'; end if;
    end;
  end loop;
end; $$;
revoke all on function public.create_farsiyar_class() from public;
grant execute on function public.create_farsiyar_class() to authenticated;

create or replace function public.student_get_roster(p_room_code text)
returns table(student_name text) language sql security definer set search_path = public as $$
  select jsonb_array_elements_text(c.roster) from public.farsiyar_classes c where c.room_code = upper(trim(p_room_code));
$$;
revoke all on function public.student_get_roster(text) from public;
grant execute on function public.student_get_roster(text) to anon, authenticated;

create or replace function public.student_get_class(p_room_code text, p_student_name text)
returns table(room_code text,title text,lesson_index integer,mission jsonb,notice text,board_state jsonb)
language sql security definer set search_path = public as $$
  select c.room_code,c.title,c.lesson_index,c.mission,c.notice,c.board_state from public.farsiyar_classes c
  where c.room_code = upper(trim(p_room_code)) and c.roster @> jsonb_build_array(trim(p_student_name));
$$;
revoke all on function public.student_get_class(text,text) from public;
grant execute on function public.student_get_class(text,text) to anon, authenticated;

create or replace function public.student_get_scores(p_room_code text, p_student_name text)
returns table(student_name text,points integer) language plpgsql security definer set search_path = public as $$
begin
  if not exists(select 1 from public.farsiyar_classes c where c.room_code=upper(trim(p_room_code)) and c.roster @> jsonb_build_array(trim(p_student_name))) then return; end if;
  return query select s.student_name,s.points from public.farsiyar_scores s where s.room_code=upper(trim(p_room_code)) order by s.points desc,s.student_name asc;
end; $$;
revoke all on function public.student_get_scores(text,text) from public;
grant execute on function public.student_get_scores(text,text) to anon, authenticated;

create or replace function public.award_farsiyar_points(p_room_code text,p_student_name text,p_delta integer)
returns integer language plpgsql security definer set search_path = public as $$
declare new_points integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  if p_delta is null or p_delta < -3 or p_delta > 3 or p_delta = 0 then raise exception 'INVALID_DELTA'; end if;
  if not exists(select 1 from public.farsiyar_classes c where c.room_code=upper(trim(p_room_code)) and c.owner_id=auth.uid()) then raise exception 'NOT_CLASS_OWNER' using errcode='42501'; end if;
  if not exists(select 1 from public.farsiyar_classes c where c.room_code=upper(trim(p_room_code)) and c.roster @> jsonb_build_array(trim(p_student_name))) then raise exception 'STUDENT_NOT_IN_ROSTER'; end if;
  insert into public.farsiyar_scores(room_code,student_name,points,updated_at) values(upper(trim(p_room_code)),trim(p_student_name),greatest(0,p_delta),now())
  on conflict(room_code,student_name) do update set points=greatest(0,public.farsiyar_scores.points+p_delta),updated_at=now() returning points into new_points;
  return new_points;
end; $$;
revoke all on function public.award_farsiyar_points(text,text,integer) from public;
grant execute on function public.award_farsiyar_points(text,text,integer) to authenticated;

create or replace function public.clear_farsiyar_scores(p_room_code text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists(select 1 from public.farsiyar_classes where room_code=upper(trim(p_room_code)) and owner_id=auth.uid()) then raise exception 'NOT_CLASS_OWNER'; end if;
  delete from public.farsiyar_scores where room_code=upper(trim(p_room_code));
end; $$;
revoke all on function public.clear_farsiyar_scores(text) from public;
grant execute on function public.clear_farsiyar_scores(text) to authenticated;

alter table public.farsiyar_classes replica identity full;
alter table public.farsiyar_responses replica identity full;
alter table public.farsiyar_scores replica identity full;
do $$ begin alter publication supabase_realtime add table public.farsiyar_classes; exception when duplicate_object then null; when undefined_object then raise notice 'Enable Supabase Realtime publication.'; end $$;
do $$ begin alter publication supabase_realtime add table public.farsiyar_responses; exception when duplicate_object then null; when undefined_object then raise notice 'Enable Supabase Realtime publication.'; end $$;
do $$ begin alter publication supabase_realtime add table public.farsiyar_scores; exception when duplicate_object then null; when undefined_object then raise notice 'Enable Supabase Realtime publication.'; end $$;
